### PR TITLE
Christoph backend

### PR DESCRIPTION
**Pull request by Christoph98**
- Made new folder within the code directory called "data", containing 3 things:
    - The entire spreadsheet of data
    - Python code that extracts desired json data from xlsx
    - JSON file that the code creates

### CODE REVIEW

**Comment by thyo9470** [comment]
I am trying to open the JSON file (country_electricity.json) but I am getting parsing errors. I have tried opening it with python and [this website](https://jsonformatter.org/json-pretty-print) and neither were able to open it. Would you be able to create a javascript script file that opens the JSON file to ensure it works and so we have an example? Thanks!

**Comment by thyo9470** [comment]
Also I am not seeing any .bin files, but it wouldn't hurt adding it to the git ignore. @JoyMace Where did you see the .bin file?

**Comment by Christoph98** [comment]
I don't see any bin files either, where do you see it Joy?
That's really odd that you're struggling to open the JSON, let me see if I can open it!

**Comment by JoyMace** [comment]
BIN +673 KB code/data/SE4ALLEXCEL.xlsx 

It is just the spreadsheet, being handled as a binary file

**Comment by Christoph98** [comment]
Huh... I can turn it into a csv and maybe then it wont be treated as a binary file... 
Also Thomas, I'm struggling to run the code right now, and don't really have time right now to look at it. I'll work on it at a later time this week.

**Comment by thyo9470** [comment]
@Christoph98 ok, when do you think you'll have time to finish it. Just trying to make sure we keep to our schedule.

**Comment by thyo9470** [comment]
Also, I think a CSV would probably be preferred since it is a simpler file format than xlsx.

**Comment by Christoph98** [comment]
I'm taking my small laptop to San Diego and will see if I have time to do it there. If not, I will be able to do it on Sunday.

**Comment by Christoph98** [comment]
I'm gonna close this request as I have since updated the data.

**Pull request closed without merging**
